In [18]:
import plotly
from plotly.graph_objs import Scatter, Layout
import numpy as np
import os
import pandas as pd
import plotly.graph_objects as go
from plotly.offline import plot

%matplotlib inline

In [19]:
discount = 0.02
ConsiderTC = 1
ConsiderMB = 1
informal = 0.0
scenario = 'val'
file_tag = 'ALL'

In [20]:
# codemap = pd.read_csv('codemaps.csv')
countries_info = pd.read_csv('data/dl1_countrycodeorg_country_name.csv', encoding='latin-1')
countries_info = countries_info[['Country Code', 'Region', 'Income group', 'WBCountry', 'country']]
codemap = countries_info.dropna()

In [21]:
# df = pd.read_csv('imputation/aggregated_results_imputated_%s.csv'%(discount))
result_path = f'results/aggregate_results_imputed_{file_tag}.csv'
if not os.path.exists(result_path):
    result_path = 'results/aggregate_results_imputed.csv'
df_input = pd.read_csv(result_path)
df = df_input[(df_input['discount']==discount)&
                (df_input['ConsiderTC']==ConsiderTC)&
                (df_input['ConsiderMB']==ConsiderMB)&
                (df_input['informal']==informal)&
                (df_input['scenario']==scenario)]

# df = df[df['tax'] >0 ]
df.head()
df = df.groupby('Country Code').sum()
df = df.reset_index()
# discount = 0
# scenario = 'val'
# disease = 'Liver cancer'
# df = pd.read_csv('results/aggregate_results_discount_0.csv')
# df = df[(df['disease'] == disease) & (df['scenario'] == scenario)]
# df = df.reset_index().drop(columns=['index'])
# df.head()
# print(len(df))

In [22]:
test_df = df.copy()
test_df = df.sort_values(by='tax')

In [23]:
test_df

,Country Code,scenario,ConsiderTC,ConsiderMB,informal,discount,GDPloss,tax,pc_loss,disease
108,LUX,val,1,1,0.0,0.02,1.995748,0.000835,2790.855803,ASCVD
41,COM,val,1,1,0.0,0.02,0.091125,0.000981,78.120922,ASCVD
131,NGA,val,1,1,0.0,0.02,39.738465,0.001319,133.272469,ASCVD
93,KEN,val,1,1,0.0,0.02,14.691263,0.001326,201.595049,ASCVD
172,SWZ,val,1,1,0.0,0.02,0.433168,0.001464,306.693714,ASCVD
...,...,...,...,...,...,...,...,...,...,...
107,LTU,val,1,1,0.0,0.02,30.529167,0.008147,12756.296296,ASCVD
178,TJK,val,1,1,0.0,0.02,19.419209,0.009629,1521.769516,ASCVD
54,EGY,val,1,1,0.0,0.02,581.756853,0.009888,4447.411941,ASCVD
17,BGR,val,1,1,0.0,0.02,71.132357,0.013109,11563.627771,ASCVD
65,GEO,val,1,1,0.0,0.02,29.635865,0.013520,7866.800379,ASCVD

In [24]:
df['Country Code'].unique(), len(df['Country Code'].unique())

(array(['AFG', 'AGO', 'ALB', 'AND', 'ARE', 'ARG', 'ARM', 'ASM', 'ATG',
        'AUS', 'AUT', 'AZE', 'BDI', 'BEL', 'BEN', 'BFA', 'BGD', 'BGR',
        'BHR', 'BHS', 'BIH', 'BLR', 'BLZ', 'BMU', 'BOL', 'BRA', 'BRB',
        'BRN', 'BTN', 'BWA', 'CAF', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV',
        'CMR', 'COD', 'COG', 'COK', 'COL', 'COM', 'CPV', 'CRI', 'CUB',
        'CYP', 'CZE', 'DEU', 'DJI', 'DMA', 'DNK', 'DOM', 'DZA', 'ECU',
        'EGY', 'ERI', 'ESP', 'EST', 'ETH', 'FIN', 'FJI', 'FRA', 'FSM',
        'GAB', 'GBR', 'GEO', 'GHA', 'GIN', 'GMB', 'GNB', 'GNQ', 'GRC',
        'GRD', 'GRL', 'GTM', 'GUM', 'GUY', 'HND', 'HRV', 'HTI', 'HUN',
        'IDN', 'IND', 'IRL', 'IRN', 'IRQ', 'ISL', 'ISR', 'ITA', 'JAM',
        'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KHM', 'KIR', 'KNA', 'KOR',
        'KWT', 'LAO', 'LBN', 'LBR', 'LBY', 'LCA', 'LKA', 'LSO', 'LTU',
        'LUX', 'LVA', 'MAR', 'MCO', 'MDA', 'MDG', 'MDV', 'MEX', 'MHL',
        'MKD', 'MLI', 'MLT', 'MMR', 'MNE', 'MNG', 'MNP', 'MOZ', 'MRT',
        'MUS', 'MWI', 'MYS', 'NAM', 'NER', 'NGA', 'NIC', 'NIU', 'NLD',
        'NOR', 'NPL', 'NRU', 'NZL', 'OMN', 'PAK', 'PAN', 'PER', 'PHL',
        'PLW', 'PNG', 'POL', 'PRI', 'PRK', 'PRT', 'PRY', 'PSE', 'QAT',
        'ROU', 'RUS', 'RWA', 'SAU', 'SDN', 'SEN', 'SGP', 'SLB', 'SLE',
        'SLV', 'SMR', 'SOM', 'SRB', 'SSD', 'STP', 'SUR', 'SVK', 'SVN',
        'SWE', 'SWZ', 'SYC', 'SYR', 'TCD', 'TGO', 'THA', 'TJK', 'TKL',
        'TKM', 'TLS', 'TON', 'TTO', 'TUN', 'TUR', 'TUV', 'TWN', 'TZA',
        'UGA', 'UKR', 'URY', 'USA', 'UZB', 'VCT', 'VEN', 'VIR', 'VNM',
        'VUT', 'WSM', 'YEM', 'ZAF', 'ZMB', 'ZWE'], dtype=object),
 204)

# total burden

In [ ]:
fig = go.Figure(data=go.Choropleth(
        locations = df['Country Code'],
        z = df['tax']*100,
        colorscale = [[0,"rgb(158, 59, 59)"],
                      [0.5,"rgb(210, 83, 83)"],
                      # [0.25,"rgb(234, 123, 123)"],
                      [1,"rgb(255, 234, 211)"]],
        reversescale = True,
        colorbar_title='% of Total GDP<br>During 2020-2050<br>',
        autocolorscale = False,
        marker = dict(
            line = dict (
                color = 'rgb(0,0,0)',
                width = 0.5
            ) ),
        # colorbar_title='%',
        colorbar = dict(
            len = 0.4,
            thickness = 15,
            tick0= 0,
            tickmode='array',
            outlinewidth=1,
            outlinecolor='rgb(0,0,0)',
            tickvals= [0.5, 1],
            ticktext=['0.5%','1.0%']
        ),
            
))
fig.update_layout(
    font=dict(
        # family="Courier New, monospace",
        family="Helvetica",
        size=10,
        color='black'
        # color="#7f7f7f"
    ),
#     title = 'Economic Burden of Road Injuries During 2020-2050',
    geo = dict(
        showframe = False,
        showcoastlines = True,
        coastlinecolor = "rgb(0,0,0)",
        coastlinewidth = 0.5,
        showcountries = True,
        countrycolor = "rgb(0, 0, 0)",
        countrywidth = 0.5,
        showlakes = False,
        projection_type='equirectangular',
        lataxis_range=[-58, 90],
    ),
    margin = {'l':0,'r':0,'t':0,'b':0}

)

fig.data[0].colorbar.x=0.02
fig.data[0].colorbar.y=0.33
fig.show()

# fig.update_layout(width=700, height=500)
# fig.write_image("tables/figure_1.pdf")
# fig.write_image("tables/figure_1.svg")
# fig.write_image("tables/figure_1.png", scale=3)

In [ ]:
df['logGDPloss'] = df['GDPloss'].apply(np.log10)

In [95]:
df

,Country Code,scenario,ConsiderTC,ConsiderMB,informal,discount,GDPloss,tax,pc_loss,disease,logGDPloss
0,AFG,val,1,1,0.0,0.02,5.594792,0.003128,106.947379,ASCVD,0.747784
1,AGO,val,1,1,0.0,0.02,8.735737,0.001764,164.531880,ASCVD,0.941300
2,ALB,val,1,1,0.0,0.02,5.026771,0.003767,1865.653702,ASCVD,0.701289
3,AND,val,1,1,0.0,0.02,0.368292,0.003092,4746.769000,ASCVD,-0.433807
4,ARE,val,1,1,0.0,0.02,65.776467,0.003071,6262.037405,ASCVD,1.818071
...,...,...,...,...,...,...,...,...,...,...,...
199,WSM,val,1,1,0.0,0.02,0.132370,0.003353,569.610024,ASCVD,-0.878211
200,YEM,val,1,1,0.0,0.02,8.039513,0.003050,204.148160,ASCVD,0.905230
201,ZAF,val,1,1,0.0,0.02,46.687219,0.002372,683.288270,ASCVD,1.669198
202,ZMB,val,1,1,0.0,0.02,5.809863,0.002649,206.872205,ASCVD,0.764166
203,ZWE,val,1,1,0.0,0.02,2.248525,0.001529,116.649439,ASCVD,0.351898

In [119]:
fig = go.Figure(data=go.Choropleth(
        locations = df['Country Code'],
        z = df['logGDPloss'],
        colorscale = [[0,"rgb(158, 59, 59)"],
                      # [0.25,"rgb(210, 83, 83)"],
                      [0.25,"rgb(234, 123, 123)"],
                      [1,"rgb(255, 234, 211)"]],
        reversescale=True,
        # colorscale = 'Blues', 
        autocolorscale = False,
        marker = dict(
            line = dict (
                color = 'rgb(0,0,0)',
                width = 0.5
            ) ),
        # colorbar_title='$Billion',
        colorbar_title='Macroeconomic burden<br>due to ASCVD in 2020-2050<br>(in billions of 2017 INT$)<br>',
        colorbar = dict(
            len = 0.3,
            thickness = 15,
            tick0= 0,
            tickmode='array',
            outlinewidth=1,
            outlinecolor='rgb(0,0,0)',
            tickvals= [-2,-1,0,1,2,3],
            ticktext=['$0.01','$0.1','$1','$10','$100','$1000']),
))
fig.update_layout(
    font=dict(
        family="Helvetica",
        size=8,
        color='black'
    ),
    margin = {'l':0,'r':0,'t':0,'b':0},
    
    geo = dict(
        showframe = False,
        showcoastlines = True,
        coastlinecolor = "rgb(0,0,0)",
        coastlinewidth = 0.5,
        showcountries = True,
        countrycolor = "rgb(0, 0, 0)",
        countrywidth = 0.5,
        showlakes = False,
        projection_type='equirectangular',
        lataxis_range=[-58, 90],
    )
)

fig.data[0].colorbar.x=0.02
fig.data[0].colorbar.y=0.33
fig.show()

# fig.update_layout(width=700, height=500)
# fig.write_image("tables/figure_2.pdf")
# fig.write_image("tables/figure_2.svg")
# fig.write_image("tables/figure_2.png", scale=3)

## Supplementary Figures

In [12]:
ihme_candidates = ['data_diabetes/IHME.csv', 'prev/data_diabetes/IHME.csv', 'bigdata/data_diabetes/IHME.csv']
ihme_path = next((p for p in ihme_candidates if os.path.exists(p)), None)
if ihme_path is None:
    raise FileNotFoundError('IHME.csv not found. Expected one of: ' + ', '.join(ihme_candidates))
df_IHME = pd.read_csv(ihme_path)
df_IHME = df_IHME[(df_IHME['year']==2019) & (df_IHME['metric']=='Rate')]
df_IHME = df_IHME.rename(columns={'location':'country'})
cn = countries_info[["Country Code", "country"]]
df_IHME = df_IHME.merge(cn, on='country',how='inner')
df_IHME = df_IHME[['Country Code','cause','val','measure']]
data = pd.pivot_table(df_IHME, columns='measure',values='val',index=['Country Code'])

In [13]:
data.loc['TWN',:] = data.loc['CHN',:]
data = data.reset_index()

In [14]:
fig = go.Figure(data=go.Choropleth(
        locations = data['Country Code'],
        z = data['Incidence']/100.0,
        colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(210, 240, 255)"]],
        # colorscale = 'Reds',
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(0,0,0)',
                width = 0.5
            ) ),
        colorbar = dict(
            len = 0.4,
            thickness = 15,
            tickwidth = 0.2,
            tick0= 0.2,
            # title = 'Total cancers <br>Incidence Per 1,000'),
            title = 'Incidence'),
            
))
fig.update_layout(
    font=dict(
        # family="Courier New, monospace",
        family="Times New Roman",
        size=8,
        # color="#7f7f7f"
    ),
    margin = {'l':0,'r':0,'t':0,'b':0},
#     title = 'Economic Burden of Road Injuries During 2020-2050',
    geo = dict(
        showframe = False,
        showcoastlines = False,
                showcountries = True,
        countrycolor = "rgb(0, 0, 0)",
        countrywidth = 0.5,
        projection_type='equirectangular',
        lataxis_range=[-60, 90],
    )
)

fig.data[0].colorbar.x=0.0
fig.data[0].colorbar.y=0.4

# fig.show()
# plot(fig)
fig.write_image("tables/figure_S1.pdf")

In [15]:
fig = go.Figure(data=go.Choropleth(
        locations = data['Country Code'],
        z = data['Deaths']/100.0,
        colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(210, 240, 255)"]],
        # colorscale = 'Reds',
        autocolorscale = False,
        reversescale = True,
        marker = dict(
            line = dict (
                color = 'rgb(0,0,0)',
                width = 0.5
            ) ),
        colorbar = dict(
            len = 0.4,
            thickness = 15,
            tickwidth = 0.2,
            tick0= 0.2,
            title = 'Deaths'),
))
fig.update_layout(
    font=dict(
        # family="Courier New, monospace",
        family="Times New Roman",
        size=8,
        # color="#7f7f7f"
    ),
    margin = {'l':0,'r':0,'t':0,'b':0},
#     title = 'Economic Burden of Road Injuries During 2020-2050',
    geo = dict(
        showframe = False,
        showcoastlines = False,
                showcountries = True,
        countrycolor = "rgb(0, 0, 0)",
        countrywidth = 0.5,
        projection_type='equirectangular',
        lataxis_range=[-60, 90],
    )
)

fig.data[0].colorbar.x=0.0
fig.data[0].colorbar.y=0.4

# plot(fig)
# fig.show()
fig.write_image("tables/figure_S2.pdf")

In [16]:
fig = go.Figure(data=go.Choropleth(
        locations = data['Country Code'],
        z = data['Prevalence']/100.0,
        colorscale = [[0,"rgb(5, 10, 172)"],[0.35,"rgb(40, 60, 190)"],[0.5,"rgb(70, 100, 245)"],\
            [0.6,"rgb(90, 120, 245)"],[0.7,"rgb(106, 137, 247)"],[1,"rgb(210, 240, 255)"]],
        # colorscale = 'Reds',
        autocolorscale = False,
        reversescale = True,
        
    
        marker = dict(
            line = dict (
                color = 'rgb(0,0,0)',
                width = 0.5
            ) ),
        colorbar = dict(
            len = 0.4,
            thickness = 15,
            tickwidth = 0.2,
            tick0= 0.2,
            title = 'Prevalence'),
))
fig.update_layout(
    font=dict(
        # family="Courier New, monospace",
        family="Times New Roman",
        size=8,
        # color="#7f7f7f"
    ),
    margin = {'l':0,'r':0,'t':0,'b':0},
#     title = 'Economic Burden of Road Injuries During 2020-2050',
    geo = dict(
        showframe = False,
        showcoastlines = False,
                showcountries = True,
        countrycolor = "rgb(0, 0, 0)",
        countrywidth = 0.5,
        projection_type='equirectangular',
        lataxis_range=[-60, 90],
    )
)

fig.data[0].colorbar.x=0.0
fig.data[0].colorbar.y=0.4

# plot(fig)
# fig.show()
fig.write_image("tables/figure_S3.pdf")